# Generated by Django 5.0.2 on 2024-02-11 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiresty', '0002_rename_subjects_taught_subject_grade_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
    ]
